Repository numixproject/numix-core, pull requests merged in 2021-09, with the labels that each got.

#5286 Icons for Torchlight
  data.json
  icons/circle/48/torchlight.svg
  icons/square/48/torchlight.svg
Labels: merge

#5205 Icons for Clustertruck
  data.json
  icons/circle/48/clustertruck.svg
  icons/square/48/clustertruck.svg
Labels: merge

#5470 Icons for Cyan
  data.json
  icons/circle/48/cyan.svg
  icons/square/48/cyan.svg
Labels: merge

#5753 Use Github Actions instead
  .github/workflow-assets/test-requirements.txt
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: script

#4780 Script Cleanup
  .editorconfig
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/workflow-assets/test-requirements.txt
  .github/workflows/markdownlint-config.json
  .github/workflows/test.yml
  .gitignore
  LICENSE
  data.json
  gen.py
  icons/tags.py
  tests/db_entry.py
  tests/duplicates.py
  tests/icon_cache.py
  tests/icons_entry.py
  tests/ordered_db.py
  tests/pycodestyle.sh
  tests/schema.json
  tests/schema.py
  tests/utils.py
Labels: merge, script

#5755 Documentation Improvements
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-core.md
  .github/ISSUE_TEMPLATE/bug-icons.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/linux-icon-reqest.md
  .github/ISSUE_TEMPLATE/request-chrome.md
  .github/ISSUE_TEMPLATE/request-linux.md
  .github/ISSUE_TEMPLATE/request-steam.md
  .github/ISSUE_TEMPLATE/request-windows.md
  README.md
  data.json
  icons/README.md
  icons/tags.py
Labels: merge, script
